---
- hosts: all
  become: true

  tasks:
  - name: update repo index
    ansible.builtin.apt:
      update_cache: yes

  - name: Install Apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: install suppor for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
