---
- hosts: all
  become: true

  tasks:

  - name: Install Apache2 package, support for php and update repo index
    ansible.builtin.package:
      name:
        - "{{ apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

