---
- hosts: all
  become: true

  tasks:
  - name: update repo index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install Apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install suppor for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repo index
    ansible.builtin.yum:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: Install Apache2 package
    ansible.builtin.yum:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install suppor for php
    ansible.builtin.yum:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"
