---
- hosts: all
  become: true
  pre_tasks:
    - name: install update for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: Install Apache2 package
    tags: apache, ubuntu
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install suppor for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: Start apache2 on ubuntu
    tags: apache, ubuntu
    ansible.builtin.service:
      name: apache2
      state: started
      when: ansible_distribution == "Ubuntu"

  - name: copy html file for site
    tags: apache, ubuntu
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
